### ISSUE TITLE
WPF control crash while using "Find" feature

### ISSUE THREAD

**Issue by fadden** [fadden/CiderPress2#22]
When finding files in the GUI, the application tries to scroll the window contents so that the found item is selected. It needs to do this in the file list and, for hierarchical filesystems, in the directory tree.

The application has a `DirectoryTreeItem` method called `BringItemIntoView` that took several hours and a couple of stackoverflow posts to figure out.  It calls an internal `VirtualizingPanel` method called `BringIndexIntoView`.  Most of the time this works, but sometimes it crashes like this:
```
 ---> System.InvalidOperationException: Cannot call StartAt when content generation is in progress.
   at System.Windows.Controls.ItemContainerGenerator.System.Windows.Controls.Primitives.IItemContainerGenerator.StartAt(GeneratorPosition position, GeneratorDirection direction, Boolean allowStartAtRealizedItem)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
[...]
   at System.Windows.Controls.VirtualizingStackPanel.BringIndexIntoView(Int32 index)
```

The next Find operation blows up while trying to traverse the TreeView.

These failures can be ignored, since ultimately it just means that the directory tree isn't getting scrolled, but it's not ideal.

Reproduction steps:
 - Open `devcdjan92.iso` (an image of the January 1992 Apple Developer CD-ROM).
 - Hit Ctrl+F, type "gsbug", click "Find Next".  That causes the first crash.
 - Click "Find Next".  That causes the second failure.
 - Continuing to click "Find Next" works without issue, until you wrap around to the top again.

Unrelated but interesting: if you select an item in the file list in the middle of a large archive, and move the scrollbar elsewhere, sometimes the file view jumps back to the item if you move the directory tree scrollbar around.  More weird interactions with virtualization?

**Comment by fadden** [comment]
Patched in v1.0.3-dev1: https://github.com/fadden/CiderPress2/releases/tag/v1.0.3-dev1

**Comment by fadden** [comment]
I just hit this again.  This time it was with a large (~500MB) Zip archive from asimov.  Same basic issue, where we're trying to scroll the list to make a certain item visible.  In this case it's failing on SelectRowByIndex(), which calls the one-arg form of dataGrid.ScrollIntoView() to try to force the virtualization system to reify the item.  That eventually calls GetCell(), which calls the two-arg form of dataGrid.ScrollIntoView(), again to try to work the WPF virtualization system.  This fails.

I'm not sure what to blame, but this is probably another opportunity for working around the issue by catching the exception and returning null.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot call StartAt when content generation is in progress.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Controls.ItemContainerGenerator.System.Windows.Controls.Primitives.IItemContainerGenerator.StartAt(GeneratorPosition position, GeneratorDirection direction, Boolean allowStartAtRealizedItem)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   at System.Windows.Controls.Primitives.DataGridRowsPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Controls.DataGrid.ScrollCellIntoView(ItemInfo info, DataGridColumn column)
   at System.Windows.Controls.DataGrid.ScrollIntoView(ItemInfo info, DataGridColumn column)
   at System.Windows.Controls.DataGrid.ScrollIntoView(Object item, DataGridColumn column)
   at cp2_wpf.WPFCommon.DataGridExtensions.GetCell(DataGrid dataGrid, DataGridRow rowContainer, Int32 column) in C:\Src\CiderPress2\cp2_wpf\WPFCommon\WPFExtensions.cs:line 277
   at cp2_wpf.WPFCommon.DataGridExtensions.SelectRowColAndFocus(DataGrid dataGrid, Int32 rowIndex, Int32 colIndex) in C:\Src\CiderPress2\cp2_wpf\WPFCommon\WPFExtensions.cs:line 304
   at cp2_wpf.MainWindow.ItemContainerGenerator_StatusChanged(Object sender, EventArgs e) in C:\Src\CiderPress2\cp2_wpf\MainWindow.xaml.cs:line 1332
   at System.Windows.Controls.ItemContainerGenerator.SetStatus(GeneratorStatus value)
   at System.Windows.Controls.ItemContainerGenerator.Generator.System.IDisposable.Dispose()
   at System.Windows.Controls.VirtualizingStackPanel.BringContainerIntoView(ItemsControl itemsControl, Int32 itemIndex)
   at System.Windows.Controls.VirtualizingStackPanel.BringIndexIntoView(Int32 index)
   at System.Windows.Controls.ItemsControl.OnBringItemIntoView(ItemInfo info)
   at System.Windows.Controls.DataGrid.ScrollIntoView(ItemInfo info)
   at System.Windows.Controls.DataGrid.ScrollIntoView(Object item)
   at cp2_wpf.WPFCommon.DataGridExtensions.SelectRowByIndex(DataGrid dataGrid, Int32 rowIndex) in C:\Src\CiderPress2\cp2_wpf\WPFCommon\WPFExtensions.cs:line 338
   at cp2_wpf.FileListItem.SetSelectionFocusByEntry(ObservableCollection`1 tvRoot, DataGrid dataGrid, IFileEntry selEntry) in C:\Src\CiderPress2\cp2_wpf\FileListItem.cs:line 307
   at cp2_wpf.FileListItem.SelectAndView(MainWindow mainWin, IFileEntry selEntry) in C:\Src\CiderPress2\cp2_wpf\FileListItem.cs:line 288
   at cp2_wpf.MainController.DoFindFiles(FindFileReq req) in C:\Src\CiderPress2\cp2_wpf\MainController.cs:line 2642
   at cp2_wpf.FindFile.FindNext_Click(Object sender, RoutedEventArgs e) in C:\Src\CiderPress2\cp2_wpf\FindFile.xaml.cs:line 121
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnAccessKey(AccessKeyEventArgs e)
   at System.Windows.Input.AccessKeyManager.ProcessKey(List`1 targets, String key, Boolean existsElsewhere, Boolean userInitiated)
   at System.Windows.Input.AccessKeyManager.ProcessKeyForSender(Object sender, String key, Boolean existsElsewhere, Boolean userInitiated)
   at System.Windows.Input.AccessKeyManager.OnKeyDown(KeyEventArgs e)
   at System.Windows.Input.AccessKeyManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at cp2_wpf.MainController.FindFiles() in C:\Src\CiderPress2\cp2_wpf\MainController.cs:line 2085
   at cp2_wpf.MainWindow.FindCmd_Executed(Object sender, ExecutedRoutedEventArgs e) in C:\Src\CiderPress2\cp2_wpf\MainWindow.xaml.cs:line 561
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at cp2_wpf.App.Main()
```
